"""Export the canonical EVENT_TYPES list as an ESM artifact the dashboard imports (B5.6).

Closes the B4.7 SSE-wiring hygiene gap: the dashboard's event-dispatch list is no longer a hand-kept
copy — it is DERIVED from the Python registry. Regenerate with `npm run generate-events` (or
`python -m devharness.events.manifest <path>`); CI fails on drift (tests/runtime/test_events_js_derived.py).
"""

import sys
from pathlib import Path

from devharness.events.registry import EVENT_TYPES

_HEADER = (
    "// GENERATED by runtime/devharness/events/manifest.py — do not edit by hand.\n"
    "// Source of truth: runtime/devharness/events/registry.py EVENT_TYPES.\n"
    "// Regenerate: npm run generate-events. CI fails on drift (test_events_js_derived.py).\n"
)

# default outputs (relative to repo root): the dashboard ESM list and the Rust sidecar catalog.
DEFAULT_OUTPUT = Path(__file__).resolve().parents[3] / "dashboard" / "src" / "events.generated.js"
DEFAULT_RUST_OUTPUT = Path(__file__).resolve().parents[3] / "sidecar" / "src" / "event_catalog.generated.rs"

_RUST_HEADER = (
    "// GENERATED by runtime/devharness/events/manifest.py — do not edit by hand.\n"
    "// Source of truth: runtime/devharness/events/registry.py EVENT_TYPES.\n"
    "// Regenerate: python -m devharness.events.manifest. CI fails on drift (test_event_catalog_rs_derived.py).\n"
)


def event_type_names() -> list:
    """The canonical event-type names, in registry (insertion) order."""
    return list(EVENT_TYPES.keys())


def render() -> str:
    lines = [_HEADER, "export const EVENT_TYPES = [\n"]
    lines += [f"  '{name}',\n" for name in event_type_names()]
    lines.append("];\n")
    return "".join(lines)


def render_rust() -> str:
    lines = [_RUST_HEADER, "pub const EVENT_CATALOG: &[&str] = &[\n"]
    lines += [f'    "{name}",\n' for name in event_type_names()]
    lines.append("];\n")
    return "".join(lines)


def write_manifest(path=None) -> Path:
    out = Path(path) if path is not None else DEFAULT_OUTPUT
    out.write_text(render(), encoding="utf-8")
    return out


def write_rust_catalog(path=None) -> Path:
    """Write the sidecar's EVENT_CATALOG (#H9 — was hand-frozen at 7 of 49 types)."""
    out = Path(path) if path is not None else DEFAULT_RUST_OUTPUT
    out.write_text(render_rust(), encoding="utf-8")
    return out


if __name__ == "__main__":
    target = write_manifest(sys.argv[1] if len(sys.argv) > 1 else None)
    rust = write_rust_catalog()
    sys.stdout.write(f"wrote {len(event_type_names())} event types to {target} and {rust}\n")
